// <auto-generated />
namespace SV_16T1021182.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add1st : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add1st));
        
        string IMigrationMetadata.Id
        {
            get { return "202001040056282_add1st"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
